### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pedrodj** [PowerScript/facebrok#1]
Hi Redtoor,

I'm trying to install the script, specified all SQL parameters but

"The requested URL /facebrok/croak/install/startgame was not found on this server."

file startgame.php is presente on the server: any suggestion?

Thank you

Regards

**Comment by RedToor** [comment]
The potential problem is the .htaccess file, the server interprets the file without extension well (.php) and continues executing tasks.

the solution is to edit the file croak/install/install.php line 13
action = "startGame" by action = "startgame.php"

try this and tell me how it go.
Greetings.
