### ISSUE TITLE
it's blocked on http://www.xxxxx/croak/index.php?action=login

### ISSUE THREAD

**Issue by ziflar** [PowerScript/facebrok#2]
hello freind.
i've tried to install facebrook on hotinger.
but After entering the login information of the database .
i have install was successfully
but the webpage is blocked on 
http://www.xxxxx/croak/index.php?action=login

checkeing the phpmyadmin on the hostinger control panel : 
no database was created.
please try to upload facebrook on hostinger and edit all error's

**Comment by RedToor** [comment]
Hi, the install cannot create a new database, you might created the database from the control panel of hostinger.

**Comment by ziflar** [comment]
@RedToor 
hello ,i've used facebrook before and all work very fine .
now the database is created from cpanel.i fill all database info in the install panel .i've install  was successfully as message  but the webpage is blocked on
http://www.xxxxx/croak/index.php?action=login

please try it on hostinger to see and edit

**Comment by RedToor** [comment]
Import diretly the database to mysql.
