### ISSUE TITLE
Missing configuration.php

### ISSUE THREAD

**Issue by digitalshuffler** [PowerScript/facebrok#3]
On first installation it returns code 500
[php7:error] [pid 6067] [client 127.0.0.1:42754] PHP Fatal error:  require_once(): Failed opening required 'configuration.php' (include_path='.:') in /srv/http/croak/core.function.php on line 7

I didn't see this file in any place

**Comment by RedToor** [comment]
The file is generated when is installing, [here](https://github.com/PowerScript/facebrok/blob/master/croak/install/install.php#L37) you can see it. you can re-install or made the file manually.
